version: 2
jobs:
  build:
    docker:
      - image: circleci/android@sha256:5cdc8626cc6f13efe5ed982cdcdb432b0472f8740fed8743a6461e025ad6cdfc

    working_directory: ~/DesafioPicpay

    environment:
      JVM_OPTS: -Xmx3200m
      CIRCLE_JDK_VERSION: oraclejdk8

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Ktlint
          command: ./gradlew ktlint

      - run:
          name: Detekt
          command: ./gradlew detektCheck

      - run:
          name: Android lint
          command: ./gradlew lint

      - run:
          name: Setup emulator
          command: sdkmanager "sdkmanager "system-images;android-21;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-21;default;armeabi-v7a""

      - run:
           name: Launch emulator
           command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
           background: true

      - run:
            name: Wait emulator
            command: |
                circle-android wait-for-boot
                sleep 30
                adb shell input keyevent 82

      - run:
          name: Run Tests and generate Code Coverage
          command: ./gradlew jacocoTestReport

      - run:
          name: Upload code coverage data
          command: ./gradlew coveralls

      - store_artifacts:
            path: app/build/reports/jacoco/jacocoTestReport
            destination: coverage-report

      - store_artifacts:
            path: network/build/reports/jacoco/jacocoTestReport
            destination: coverage-report

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}