version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha

    working_directory: ~/DesafioPicpay

    environment:
      JVM_OPTS: -Xmx3200m
      CIRCLE_JDK_VERSION: oraclejdk8

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Ktlint
          command: ./gradlew ktlint

      - run:
          name: Detekt
          command: ./gradlew detektCheck

      - run:
          name: Android lint
          command: ./gradlew lint

      - run:
          name: Run Tests and generate Code Coverage
          command: ./gradlew jacocoTestReport

      - run:
          name: Upload code coverage data
          command: ./gradlew coveralls

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}