version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha

    working_directory: ~/DesafioPicpay

    environment:
      JVM_OPTS: -Xmx3200m
      CIRCLE_JDK_VERSION: oraclejdk8

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Ktlint
          command: ./gradlew ktlint

      - run:
          name: Detekt
          command: ./gradlew detektCheck

      - run:
          name: Android lint
          command: ./gradlew lint

      - run:
          name: Launch emulator
          command: emulator -avd circleci-android22 -no-audio -no-window:
            background: true
            parallel: true

      - run:
          name: Wait emulator
          command: |
            circle-android wait-for-boot
            sleep 30
            adb shell input keyevent 82

      - run:
          name: Run Tests and generate Code Coverage
          command: ./gradlew jacocoTestReport

      - run:
          name: Upload code coverage data
          command: ./gradlew coveralls

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}